### ISSUE TITLE
CTGP-7 is not Present in Any Form on this Github Project

### ISSUE THREAD

**Issue by Guest7468** [susbaconhairman/ctgp-7-extracted#1]
Title. It isn't there. Just the readme.md.

**Comment by susbaconhairman** [comment]
sorry i didnt have time to actually add it lmao

**Comment by CyberYoshi64** [comment]
You do know there's more than the Windows installer. The 3DS installer would handle this as well.
Also, maintaining a seperate repository outside of CTGP-7's own [update repository](https://github.com/PabloMK7/CTGP-7updates) is very messy especially on each update release. It's better to keep it centralized in the mentioned repository and I'd recommend remvoing this one.

Thank you.
- CyberYoshi64

**Comment by susbaconhairman** [comment]
damn that was quite a late response lmao
